### ISSUE TITLE
Postgres won't start due to hugepages conflct

### ISSUE THREAD

**Issue by bonnieking** [DUNE-DAQ/pocket#108]
Postgres won't start in kind and we can't turn off hugepages because of DPDK. It looks like we need to disable hugepages in the bitnami container or configure k8s to allow it. See https://github.com/kubernetes/kubernetes/issues/71233#issuecomment-447472125.

**Comment by bonnieking** [comment]
This was fixed in daq-kube.

**Comment by jcpunk** [comment]
I believe this is resolved by moving to postgresql 16 and using the `--set huge_pages=off` flag.
