### ISSUE TITLE
Questions about how to get Pocket running

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/pocket#2]
Earlier today, Giovanna mentioned that I can use the instructions on the main page of this repository to learn how to start a Pocket instance to run with my tests of the minidaqapp.

The instructions don't say anything about cloning this repository or setting up the dune-daq build environment, so I did the former and played around with, and without, the latter.

It didn't seem to matter.  I got an error message like the following when I tried "make setup.local" on lxplus and when I tried it on a test cluster at Fermilab:
```
ERROR: failed to create cluster: failed to get docker info: command "docker info --format '{{json .}}'" failed with error: exit status 1
Command Output: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make: *** [setup.local] Error 1
```

Are there different instructions that I should be using?
Thanks,
Kurt
```

**Comment by Juravenator** [comment]
Commit 7a73094498915aa6fbe9f32fc0d82af67eeab5d8 should prove more satisfying

**Comment by bonnieking** [comment]
Hi Kurt,

You don't need to set up the DUNE DAQ build environment to use pocket. Just clone the pocket repository and run `make`. You do need root on the system currently.

Make sure the docker daemon is running first.

**Comment by Juravenator** [comment]
You do _not_ need root, but you do need a docker installation (which is considered root equivalent).
